[tool.poetry]
name = "faust-demo"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
faust = "^1.10"
python = "^3.9"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

